#[derive(PartialEq, Debug, Clone)]
pub enum Token {
    Illegal,
    Eof,
    Identifier { literal: String },
    Int { literal: String },
    Assign,
    Plus,
    Minus,
    Comma,
    Semicolon,
    LeftParenthesis,
    RightParenthesis,
    LeftBracket,
    RightBracket,
    Return,
    Function,
    Let,
    False,
    True,
    Slash,
    Asterisk,
    Bang,
    If,
    Else,
    LessThan,
    GreaterThan,
    Equal,
    NotEqual,
}